sudo: false
language: cpp
python:
  - "3.5"
compiler:
  - gcc

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
  - set -e
  - g++ --version
  - cd build
  - python build.py -clean -nosamples
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kubuntu-backports
    packages:
    - cmake
    - gcc-5
    - g++-5
