- env: GCC_VERSION=5 CPP=14
      os: linux
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - valgrind
          sources:
            - ubuntu-toolchain-r-test

before_install: 
  - sudo apt-get update -qq
	- sudo apt-get install -qq gcc5
	
language: python

python:
  - "3.5"
  
script:
  - cd build/linux/cmake
  - python build.py
