sudo: false
language: cpp
python:
  - "3.5"
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
  - g++ --version
  - cd build/linux/cmake
  - python build.py
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    

